/**
 * Compose lifecycle (F5 #160)
 *
 * The ORCHESTRATOR (a deterministic `type: script` state, never a CLI agent)
 * owns the sandbox's lifetime: background processes spawned inside a
 * `claude -p`/`kimi -p` die ~5s after the agent returns, so an agent can never
 * be trusted to keep `docker compose` up across a phase or to tear it down.
 *
 * `up()` boots the target repo's `compose.openroutines.yml` (`up -d --build`,
 * per-execution project name) and blocks until the app answers a healthcheck;
 * `down()` runs `down -v` to drop the ephemeral tmpfs DB so the next run is
 * clean from seed. SECURITY: every hardening property (internal network,
 * cap_drop, no-new-privileges, non-root, tmpfs) lives in the compose file the
 * target repo ships (D18, generated by Mapping) — this module only starts and
 * stops it; executor-container sandboxing (@anthropic-ai/sandbox-runtime) is
 * F6, out of scope here.
 *
 * Deliberately decoupled from card-to-pr: the Mapping pipeline (#162) reuses it
 * to capture the visual profile. No pipeline types leak in.
 */
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

/** Path (relative to the worktree) of the per-repo sandbox compose file (D18). */
export const DEFAULT_COMPOSE_FILE = "docs/openroutines/compose.openroutines.yml";
/** Loopback + fixed host port per the reference compose (04-INFRA-MAQUINA.md: `127.0.0.1:4000:3000`). */
export const DEFAULT_BASE_URL = "http://127.0.0.1:4000";

/** Runs `docker <args>` in `cwd`; the seam tests inject to avoid a real daemon. */
export type ComposeRunner = (args: string[], cwd: string) => Promise<{ stdout: string; stderr: string }>;
/** Probes `url`, resolving to the HTTP status (0 on a network error — server not up yet). */
export type HealthProbe = (url: string) => Promise<number>;

export interface ComposeHandle {
  baseUrl: string;
  /** docker compose `-p` project — pass the same executionId to `down()` to target this stack. */
  project: string;
}

export interface ComposeUpOptions {
  worktreePath: string;
  executionId: string;
  composeFile?: string;
  baseUrl?: string;
  healthPath?: string;
  timeoutMs?: number;
  intervalMs?: number;
  run?: ComposeRunner;
  probe?: HealthProbe;
}

export interface ComposeDownOptions {
  worktreePath: string;
  executionId: string;
  composeFile?: string;
  run?: ComposeRunner;
}

/**
 * docker compose project name: lowercase, `[a-z0-9_-]` only. Derived from the
 * executionId so `up`/`down` address the same stack, and prefixed/capped so an
 * odd execution id can't produce an invalid project name.
 */
export const composeProject = (executionId: string): string =>
  `or-${executionId.toLowerCase().replace(/[^a-z0-9_-]/g, "-")}`.slice(0, 60);

const defaultRun: ComposeRunner = (args, cwd) => execFileAsync("docker", args, { cwd });

const defaultProbe: HealthProbe = async (url) => {
  try {
    const res = await fetch(url, { method: "GET" });
    return res.status;
  } catch {
    return 0;
  }
};

const delay = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/**
 * Boot the sandbox and wait until `baseUrl` answers 2xx/3xx. On health timeout
 * this THROWS after the containers were started — the caller MUST wrap the
 * whole phase so its `finally` calls `down()` regardless (the started stack
 * still needs tearing down). `--build` because the app runs the branch the
 * agent just edited; `-d` so control returns to the orchestrator.
 */
export const up = async (opts: ComposeUpOptions): Promise<ComposeHandle> => {
  const composeFile = opts.composeFile ?? DEFAULT_COMPOSE_FILE;
  const baseUrl = opts.baseUrl ?? DEFAULT_BASE_URL;
  const project = composeProject(opts.executionId);
  const run = opts.run ?? defaultRun;
  const probe = opts.probe ?? defaultProbe;
  const timeoutMs = opts.timeoutMs ?? 120_000;
  const intervalMs = opts.intervalMs ?? 1_000;

  await run(["compose", "-f", composeFile, "-p", project, "up", "-d", "--build"], opts.worktreePath);

  const healthUrl = `${baseUrl}${opts.healthPath ?? "/"}`;
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const status = await probe(healthUrl);
    if (status >= 200 && status < 400) return { baseUrl, project };
    if (Date.now() >= deadline) {
      throw new Error(
        `compose-lifecycle: ${healthUrl} did not become healthy within ${timeoutMs}ms (last status ${status})`
      );
    }
    await delay(intervalMs);
  }
};

/**
 * Tear the sandbox down. `-v` drops the ephemeral volumes (the tmpfs Postgres)
 * so the next run is clean from seed. Best-effort by contract: the caller runs
 * this in a `finally`, so any error here must be caught THERE and never mask
 * the phase's own failure.
 */
export const down = async (opts: ComposeDownOptions): Promise<void> => {
  const composeFile = opts.composeFile ?? DEFAULT_COMPOSE_FILE;
  const project = composeProject(opts.executionId);
  const run = opts.run ?? defaultRun;
  await run(["compose", "-f", composeFile, "-p", project, "down", "-v"], opts.worktreePath);
};
